//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Tutorial1
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Tutorial1";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Tutorial1";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID Tutorial1DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Tutorial1CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID Tutorial1ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Tutorial1CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewTutorial1ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Tutorial1CommandSetId), 0x0001);
	
		// Package identifier
		public const string Tutorial1PackageId = "c133594e-9f6e-4202-b9f8-7b14fa062c5c";
		
		// Editor factory identifier
		public const string Tutorial1EditorFactoryId = "50ad311b-c3ef-46e2-af39-913b444c1f0f";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string Tutorial1ModelExplorerToolWindowId = "37c3bfce-9ee0-4c8e-8a5c-3001884c81ed";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.Tutorial1
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string Tutorial1CommandSetId = "c043f969-f82f-4bbc-9b37-39bbe257a93f";
	}
}